# Generated by Django 5.2 on 2025-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
