# Generated by Django 5.2 on 2025-04-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0002_alter_item_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
