# Generated by Django 5.2 on 2025-04-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register1', '0003_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
            ],
        ),
    ]
