# Generated by Django 5.2 on 2025-04-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
